# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3
#
# production:
#   <<: *default
#   database: db/production.sqlite3

development:
  adapter: postgresql
  database: xrdq_development
  encoding: utf8
  username: rchang
  password:
  host: localhost

production:
  adapter: postgresql
  database: xrdq_production
  encoding: utf8
  username: rchang
  password:
  host: localhost

test:
  adapter: postgresql
  database: xrdq_test
  encoding: utf8
  username: rchang
  password:
  host: localhost
